version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 300
    groups:
      babel:
        patterns:
        - "@babel*"
        - "babel*"
    labels:
      - "npm"
      - "dependencies"
    ignore:
      - dependency-name: "react*"
