name: Assign Reviewer

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - staging

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --workspace=.github/actions/assign-dependabot-reviewer

      - name: Determine and assign reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/actions/assign-dependabot-reviewer/assign-reviewer.mjs
